App.registerPage('challans', async (container) => {
    const { years } = await App.get('/api/years');
    if (years.length === 0) {
        container.innerHTML = `<div class="empty-state">
          <div class="empty-state-icon">🏦</div>
          <div class="empty-state-text">No financial years available. Add a year first.</div>
        </div>`;
        return;
    }
    
    if (typeof window.currentYearKey === 'undefined') {
        window.currentYearKey = '';
    }
    
    // Default to the last year if no global currentYearKey is set
    if (!window.currentYearKey || !years.find(y => y.key === window.currentYearKey)) {
        window.currentYearKey = years[years.length - 1].key;
    }

    container.innerHTML = `
        <div class="fade-in">
            <div class="page-header">
                <div>
                    <div class="section-title">Challans / Remittances</div>
                    <div class="page-desc">Enter TRRN, CRRN, and Credit Dates for each month. The totals are automatically computed based on wage records.</div>
                </div>
                <div class="toolbar-right">
                    <select class="form-select" id="challans-year-select" onchange="Challans.switchYear(this.value)">
                        ${years.map(y => `<option value="${y.key}" ${y.key === window.currentYearKey ? 'selected' : ''}>${y.label}</option>`).join('')}
                    </select>
                </div>
            </div>
            <div class="card">
                <div class="card-head">
                    <div class="card-title">Remittance Entries</div>
                    <button class="btn btn-primary btn-sm" id="btn-save-challans">Save All Changes</button>
                </div>
                <div class="table-wrap">
                    <table id="challans-table">
                        <thead>
                            <tr>
                                <th>Month</th>
                                <th style="min-width: 140px;">TRRN</th>
                                <th style="min-width: 140px;">CRRN</th>
                                <th class="num">Members</th>
                                <th class="num">A/c 1</th>
                                <th class="num">A/c 2</th>
                                <th class="num">A/c 10</th>
                                <th class="num">A/c 21</th>
                                <th class="num">A/c 22</th>
                                <th class="num">Total</th>
                                <th style="min-width: 140px;">Credit Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- rows generated by JS -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    `;
    Challans.init();
    await Challans.load();
});

const Challans = {
    remittances: [],
    
    init() {
        this.cacheDOM();
        this.bindEvents();
    },

    cacheDOM() {
        this.$tbody = document.querySelector('#challans-table tbody');
        this.$btnSave = document.getElementById('btn-save-challans');
    },

    bindEvents() {
        if(this.$btnSave) {
            this.$btnSave.addEventListener('click', () => this.saveChallansBulk());
        }
    },

    async load() {
        if (!window.currentYearKey) return;
        try {
            const res = await App.get('/api/years/' + encodeURIComponent(window.currentYearKey) + '/remittances');
            this.remittances = res.remittances || [];
            this.render();
        } catch(e) {
            console.error('Failed to load remittances', e);
        }
    },

    switchYear(key) {
        window.currentYearKey = key;
        this.load();
    },

    render() {
        if (!this.$tbody) return;
        
        this.$tbody.innerHTML = '';
        if (this.remittances.length === 0) {
            this.$tbody.innerHTML = '<tr><td colspan="11" style="text-align: center; color: var(--text3); padding: 24px;">No challans recorded for this year.</td></tr>';
            return;
        }
        
        let grandMembers = 0, grandA1 = 0, grandA2 = 0, grandA10 = 0, grandA21 = 0, grandA22 = 0, grandTot = 0;
        
        this.remittances.forEach((r, idx) => {
            const total = r.acc_01 + r.acc_02 + r.acc_10 + r.acc_21 + r.acc_22;
            grandMembers += r.members;
            grandA1 += r.acc_01;
            grandA2 += r.acc_02;
            grandA10 += r.acc_10;
            grandA21 += r.acc_21;
            grandA22 += r.acc_22;
            grandTot += total;
            
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><strong>${r.month_label}</strong></td>
                <td><input type="text" class="form-input sm challan-trrn" data-idx="${idx}" value="${r.trrn || ''}" placeholder="TRRN" style="font-family: monospace; min-width: 120px;"></td>
                <td><input type="text" class="form-input sm challan-crrn" data-idx="${idx}" value="${r.crrn || ''}" placeholder="CRRN" style="font-family: monospace; min-width: 120px;"></td>
                <td class="num">${App.fmt(r.members)}</td>
                <td class="num">${App.fmt(r.acc_01)}</td>
                <td class="num">${App.fmt(r.acc_02)}</td>
                <td class="num">${App.fmt(r.acc_10)}</td>
                <td class="num">${App.fmt(r.acc_21)}</td>
                <td class="num">${App.fmt(r.acc_22)}</td>
                <td class="num" style="font-weight: 700; color: var(--accent);">₹${App.fmt(total)}</td>
                <td><input type="date" class="form-input sm challan-date" data-idx="${idx}" value="${r.credit_date || ''}" style="min-width: 130px;"></td>
            `;
            this.$tbody.appendChild(tr);
        });
        
        const grandTr = document.createElement('tr');
        grandTr.className = 'grand-total';
        grandTr.innerHTML = `
            <td colspan="3" style="text-align: right; font-weight: 700; color: var(--text);">GRAND TOTAL</td>
            <td class="num" style="font-weight: 700;">${App.fmt(grandMembers)}</td>
            <td class="num" style="font-weight: 700;">₹${App.fmt(grandA1)}</td>
            <td class="num" style="font-weight: 700;">₹${App.fmt(grandA2)}</td>
            <td class="num" style="font-weight: 700;">₹${App.fmt(grandA10)}</td>
            <td class="num" style="font-weight: 700;">₹${App.fmt(grandA21)}</td>
            <td class="num" style="font-weight: 700;">₹${App.fmt(grandA22)}</td>
            <td class="num" style="font-weight: 800; color: var(--accent); font-size: 14px;">₹${App.fmt(grandTot)}</td>
            <td></td>
        `;
        grandTr.style.backgroundColor = 'var(--bg)';
        grandTr.style.borderTop = '2px solid var(--card-border)';
        grandTr.style.color = 'var(--text)';
        this.$tbody.appendChild(grandTr);
    },

    async saveChallansBulk() {
        const payload = this.remittances.map((r, idx) => {
            const trrnInput = this.$tbody.querySelector(`.challan-trrn[data-idx="${idx}"]`);
            const crrnInput = this.$tbody.querySelector(`.challan-crrn[data-idx="${idx}"]`);
            const dateInput = this.$tbody.querySelector(`.challan-date[data-idx="${idx}"]`);
            
            return {
                month_label: r.month_label,
                trrn: trrnInput ? trrnInput.value : '',
                crrn: crrnInput ? crrnInput.value : '',
                credit_date: dateInput ? dateInput.value : '',
                members: r.members,
                acc_01: r.acc_01,
                acc_02: r.acc_02,
                acc_10: r.acc_10,
                acc_21: r.acc_21,
                acc_22: r.acc_22
            };
        });
        
        try {
            this.$btnSave.textContent = 'Saving...';
            this.$btnSave.disabled = true;
            await App.post('/api/years/' + encodeURIComponent(window.currentYearKey) + '/remittances/bulk', { remittances: payload });
            this.$btnSave.textContent = 'Saved!';
            setTimeout(() => {
                this.$btnSave.textContent = 'Save All Changes';
                this.$btnSave.disabled = false;
            }, 2000);
            this.load();
        } catch(e) {
            alert('Error saving challans');
            console.error(e);
            this.$btnSave.textContent = 'Save All Changes';
            this.$btnSave.disabled = false;
        }
    }
};
